### ISSUE TITLE
Could not initialize state backend

### ISSUE THREAD

**Issue by metalgold** [tobilg/mesos-framework-boilerplate#1]
Hi,

I have deployed the flink-framework using Marathon (using the config provided in the mesoshq/flink-framework readme) and tried to start a sample app in flink, but then I got:

`java.lang.RuntimeException: Could not initialize state backend. 
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator.setup(AbstractStreamOperator.java:121)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.setup(AbstractUdfStreamOperator.java:82)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:276)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:212)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:271)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:212)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.<init>(OperatorChain.java:105)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:225)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:584)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.flink.configuration.IllegalConfigurationException: Cannot create the file system state backend: The configuration does not specify the checkpoint directory 'state.backend.fs.checkpointdir'
	at org.apache.flink.runtime.state.filesystem.FsStateBackendFactory.createFromConfig(FsStateBackendFactory.java:47)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.createStateBackend(StreamTask.java:695)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator.setup(AbstractStreamOperator.java:119)
	... 9 more`

My question is: how can I configure the state backend using the mathon config json/docker image?

**Comment by tobilg** [comment]
Can you open the issue in the https://github.com/mesoshq/flink-framework repo please?

**Comment by metalgold** [comment]
I wanted, but I dont't see the issues section. I'm puzzled.

**Comment by tobilg** [comment]
Sorry, you're right, I activated it now. Not sure if it was caused by the reason that it's a fork from this project... Now it should work.

**Comment by metalgold** [comment]
Thank you, I posted it there.
